# Deploy project to GitHub Pages.
name: Deploy to GitHub Pages

on: # When to run this action?
  #push: # run automatically when push
  #  branches: ['main']
  workflow_dispatch: # run manually

# Minimal permissions needed for Pages deploy. Without them action will fail.
permissions:
  contents: read
  pages: write
  id-token: write

# How to act if someone runs two deploys at same time.
concurrency:
  group: "pages"
  cancel-in-progress: true # cancels previous deploy, ensuring only one runs at same time

# Define jobs to run. They will be executed in parallel by default unless 'needs:' is specified.
jobs:
  # Prepare project for deploy.
  build:
    runs-on: ubuntu-latest # Uses a fresh Ubuntu VM.
    steps:
      # Clones your repository's code into the virtual machine, so subsequent steps can actually access your files.
      - name: Checkout
        uses: actions/checkout@v6

      # Install Node.js on the VM. Angular's build tools (npm, ng) require Node to run.
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x' # Install latest subversion of Node.js 24.
          cache: 'npm'         # Caches node_modules for speed.

      # Installs all your project's dependencies from package.json.
      - name: Install dependencies
        run: npm ci # Note: npm ci is faster/more reliable than npm install.

      # Builds your Angular app for production. This typically runs ng build as defined in your package.json scripts, outputting static files to dist/.
      - name: Build
        run: npm run build

      # Otherwise Single Page Apps wont work properly when using different path
      - name: Generate 404 fallback for GitHub Pages
        run: cp ./dist/geopark-frontend-angular/browser/index.html ./dist/geopark-frontend-angular/browser/404.html

      # Configures Pages environment (handles base path, etc.).
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # Packages dist/ as a secure artifact (temporary zip file) for the next job.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist/geopark-frontend-angular/browser # Angular builds project to "./dist/NAME_OF_APP_IN_ANGULAR/browser".

  # Actually deploy prepared project.
  deploy:
    needs: build # Must wait for build job to finish.
    runs-on: ubuntu-latest # New VM, but only starts after build succeeds.
    environment: # Targets Pages environment (protection rules + publishes the final URL).
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Deploys the artifact created in build job to your GitHub Pages site.
      # id: deployment lets previous steps reference its output (the live URL).
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
